# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ros_yolo/Detection.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Detection(genpy.Message):
  _md5sum = "0f2734d1688547c417254d6da98c0715"
  _type = "ros_yolo/Detection"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 detection_x
float64 detection_y
float64 detection_w
float64 detection_h
string detection_label
float64 detection_conf
float64 detection_center_x
float64 detection_center_y
"""
  __slots__ = ['detection_x','detection_y','detection_w','detection_h','detection_label','detection_conf','detection_center_x','detection_center_y']
  _slot_types = ['float64','float64','float64','float64','string','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       detection_x,detection_y,detection_w,detection_h,detection_label,detection_conf,detection_center_x,detection_center_y

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Detection, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.detection_x is None:
        self.detection_x = 0.
      if self.detection_y is None:
        self.detection_y = 0.
      if self.detection_w is None:
        self.detection_w = 0.
      if self.detection_h is None:
        self.detection_h = 0.
      if self.detection_label is None:
        self.detection_label = ''
      if self.detection_conf is None:
        self.detection_conf = 0.
      if self.detection_center_x is None:
        self.detection_center_x = 0.
      if self.detection_center_y is None:
        self.detection_center_y = 0.
    else:
      self.detection_x = 0.
      self.detection_y = 0.
      self.detection_w = 0.
      self.detection_h = 0.
      self.detection_label = ''
      self.detection_conf = 0.
      self.detection_center_x = 0.
      self.detection_center_y = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4d().pack(_x.detection_x, _x.detection_y, _x.detection_w, _x.detection_h))
      _x = self.detection_label
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3d().pack(_x.detection_conf, _x.detection_center_x, _x.detection_center_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.detection_x, _x.detection_y, _x.detection_w, _x.detection_h,) = _get_struct_4d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.detection_label = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.detection_label = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.detection_conf, _x.detection_center_x, _x.detection_center_y,) = _get_struct_3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4d().pack(_x.detection_x, _x.detection_y, _x.detection_w, _x.detection_h))
      _x = self.detection_label
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3d().pack(_x.detection_conf, _x.detection_center_x, _x.detection_center_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.detection_x, _x.detection_y, _x.detection_w, _x.detection_h,) = _get_struct_4d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.detection_label = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.detection_label = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.detection_conf, _x.detection_center_x, _x.detection_center_y,) = _get_struct_3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
