// Generated by gencpp from file ros_yolo/Detection.msg
// DO NOT EDIT!


#ifndef ROS_YOLO_MESSAGE_DETECTION_H
#define ROS_YOLO_MESSAGE_DETECTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_yolo
{
template <class ContainerAllocator>
struct Detection_
{
  typedef Detection_<ContainerAllocator> Type;

  Detection_()
    : detection_x(0.0)
    , detection_y(0.0)
    , detection_w(0.0)
    , detection_h(0.0)
    , detection_label()
    , detection_conf(0.0)
    , detection_center_x(0.0)
    , detection_center_y(0.0)  {
    }
  Detection_(const ContainerAllocator& _alloc)
    : detection_x(0.0)
    , detection_y(0.0)
    , detection_w(0.0)
    , detection_h(0.0)
    , detection_label(_alloc)
    , detection_conf(0.0)
    , detection_center_x(0.0)
    , detection_center_y(0.0)  {
  (void)_alloc;
    }



   typedef double _detection_x_type;
  _detection_x_type detection_x;

   typedef double _detection_y_type;
  _detection_y_type detection_y;

   typedef double _detection_w_type;
  _detection_w_type detection_w;

   typedef double _detection_h_type;
  _detection_h_type detection_h;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _detection_label_type;
  _detection_label_type detection_label;

   typedef double _detection_conf_type;
  _detection_conf_type detection_conf;

   typedef double _detection_center_x_type;
  _detection_center_x_type detection_center_x;

   typedef double _detection_center_y_type;
  _detection_center_y_type detection_center_y;





  typedef boost::shared_ptr< ::ros_yolo::Detection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_yolo::Detection_<ContainerAllocator> const> ConstPtr;

}; // struct Detection_

typedef ::ros_yolo::Detection_<std::allocator<void> > Detection;

typedef boost::shared_ptr< ::ros_yolo::Detection > DetectionPtr;
typedef boost::shared_ptr< ::ros_yolo::Detection const> DetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_yolo::Detection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_yolo::Detection_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_yolo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'ros_yolo': ['/home/cilab/project/src/ros_yolo/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_yolo::Detection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_yolo::Detection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_yolo::Detection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_yolo::Detection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_yolo::Detection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_yolo::Detection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_yolo::Detection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0f2734d1688547c417254d6da98c0715";
  }

  static const char* value(const ::ros_yolo::Detection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0f2734d1688547c4ULL;
  static const uint64_t static_value2 = 0x17254d6da98c0715ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_yolo::Detection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_yolo/Detection";
  }

  static const char* value(const ::ros_yolo::Detection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_yolo::Detection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 detection_x\n\
float64 detection_y\n\
float64 detection_w\n\
float64 detection_h\n\
string detection_label\n\
float64 detection_conf\n\
float64 detection_center_x\n\
float64 detection_center_y\n\
";
  }

  static const char* value(const ::ros_yolo::Detection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_yolo::Detection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.detection_x);
      stream.next(m.detection_y);
      stream.next(m.detection_w);
      stream.next(m.detection_h);
      stream.next(m.detection_label);
      stream.next(m.detection_conf);
      stream.next(m.detection_center_x);
      stream.next(m.detection_center_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Detection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_yolo::Detection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_yolo::Detection_<ContainerAllocator>& v)
  {
    s << indent << "detection_x: ";
    Printer<double>::stream(s, indent + "  ", v.detection_x);
    s << indent << "detection_y: ";
    Printer<double>::stream(s, indent + "  ", v.detection_y);
    s << indent << "detection_w: ";
    Printer<double>::stream(s, indent + "  ", v.detection_w);
    s << indent << "detection_h: ";
    Printer<double>::stream(s, indent + "  ", v.detection_h);
    s << indent << "detection_label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.detection_label);
    s << indent << "detection_conf: ";
    Printer<double>::stream(s, indent + "  ", v.detection_conf);
    s << indent << "detection_center_x: ";
    Printer<double>::stream(s, indent + "  ", v.detection_center_x);
    s << indent << "detection_center_y: ";
    Printer<double>::stream(s, indent + "  ", v.detection_center_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_YOLO_MESSAGE_DETECTION_H
